name: Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub_description.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: leobastiani/postgres-stellar
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: leobastiani/stellar
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
