name: docker build postgres-stellar

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        version: [11,12,13,14,15,16]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            -t leobastiani/postgres-stellar:${{ matrix.version }} \
            --build-arg="FROM=leobastiani/postgres:${{ matrix.version }}" \
            --push \
            --platform linux/386,linux/amd64,linux/arm/v5 \
            .
