name: docker build postgres-stellar

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/postgres-stellar.yaml

jobs:
  build:
    strategy:
      matrix:
        version: [11,12,13,14,15]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            --tag leobastiani/postgres-stellar:${{ matrix.version }} \
            --build-arg "FROM=leobastiani/postgres-python:${{ matrix.version }}-3.9" \
            --push \
            --platform linux/amd64,linux/arm64 \
            .
