# had to rebuild because postgres:11 image was not able to do apt update
name: docker build postgres

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [11,12,13,14,15,16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: git clone https://github.com/docker-library/postgres
      - run: |
          docker build \
            -t leobastiani/postgres:${{ matrix.version }} \
            --push \
            --platform linux/386,linux/amd64,linux/arm/v5 \
            .
        working-directory: ./postgres/${{ matrix.version }}/bullseye
