name: docker build postgres-stellar

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        version: [11,12,13,14,15,16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker build \
            -t leobastiani/postgres-stellar:${{ matrix.version }}-draft \
            --build-arg="FROM=leobastiani/postgres:${{ matrix.version }}" \
            --platform linux/386,linux/amd64,linux/arm/v5 \
            .
      - uses: kitabisa/docker-slim-action@v1
        id: slim
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: leobastiani/postgres-stellar:${{ matrix.version }}-draft
          tag: leobastiani/postgres-stellar:${{ matrix.version }}
      - run: echo "${REPORT}"
        env:
          REPORT: ${{ steps.slim.outputs.report }}
      - run: docker image push "leobastiani/postgres-stellar:${{ matrix.version }}"
